kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080  # frontend app NodePort
        hostPort: 30080
        protocol: TCP
      - containerPort: 80     # Ingress controller
        hostPort: 80
        protocol: TCP
      - containerPort: 443    # Ingress controller (TLS)
        hostPort: 443
        protocol: TCP
      - containerPort: 32000       # 👈 Add this for Jenkins
        hostPort: 32000
        protocol: TCP
